### ISSUE TITLE
Barcode patterns

### ISSUE THREAD

**Issue by j1mie** [playcanvas/playcanvas-ar#1]
Hi there, great project! Wondering if this will work with 3X3 Barcode patterns? Thanks!

**Comment by willeastcott** [comment]
Thanks for the kind words, @j1mie! 😄 Only support for the pattern markers has been added so far. It should be easy to add support for barcode markers though! I'll do that when I get a second. Or if anyone wants to submit a PR, go right ahead!

**Comment by willeastcott** [comment]
Fixed in 5b148cdce4b45411315450bc2a2b3a18ed6623dc.
