### ISSUE TITLE
Does this lib support ARToolkit's NFT and if not, what is your estimation of the effort required to support it?

### ISSUE THREAD

**Issue by fortinmike** [playcanvas/playcanvas-ar#4]
The title says it all. We have a project where we would need NFT and we are looking for a library that supports NFT in PlayCanvas. Thanks for any info!

**Comment by willeastcott** [comment]
PlayCanvasAR is implemented on top of [JSARToolkit5](https://github.com/artoolkit/jsartoolkit5). However, [JSARToolkit5 does not yet support NFT markers](https://github.com/artoolkit/jsartoolkit5/blob/master/doc/using_different_marker_types.html#L107). This is mentioned in [this issue](https://github.com/artoolkit/jsartoolkit5/issues/56). You might want to [open a new issue](https://github.com/artoolkit/jsartoolkit5/issues) entitled 'Implement NFT markers' or something similar. If JSARToolkit5 adds support, then I'll add it to PlayCanvasAR.

**Comment by dyangrun** [comment]
you can try this, is supportNFT
[https://github.com/dyangrun/PlayCanvas_jsartoolkit_support_NFT](https://github.com/dyangrun/PlayCanvas_jsartoolkit_support_NFT)
